[package]
name = "gateway"
version = "0.1.0"
authors = ["lironh <lironenk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
futures = "0.3.1"
url = "2.0"
