[package]
name = "gateway"
version = "0.2.0"
authors = ["lironh <lironenk@gmail.com>, benukhanov <ben.ukhanov@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
futures = "0.3.12"
url = "2.2.0"
dotenv = "0.15.0"